table 'DefectLine'

	measure 'Defect Count' =
			SUM ( DefectLine[Defects] )
		formatString: #,0

	measure 'Line Inspection Opportunities' =
			CALCULATE (
			SUMX (
			VALUES ( 'Line'[Line] ),
			CALCULATE ( MAX ( DefectLine[Opportunities] ) )
			),
			REMOVEFILTERS ( 'Defect' )
			)
		formatString: #,0

	measure 'Defect Records' =
			COUNTROWS ( DefectLine )
		formatString: #,0

	measure 'Defects Per Opportunity' =
			DIVIDE ( [Defect Count], [Line Inspection Opportunities] )
		formatString: 0.0%

	column 'Defect'
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: Defect

	column 'Line'
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: Line

	column 'Defects'
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: Defects

	column 'Opportunities'
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: Opportunities

	partition 'DefectLine' = m
		mode: import
		source =
			let
				Source = #table(type table [Defect = text, Line = text, Defects = nullable number, Opportunities = nullable number], {
					{"Scratch", "Line B", 0, 200},
					{"Scratch", "Line A", 8, 160},
					{"Scratch", "Line C", 3, 100},
					{"Dent", "Line B", 6, 200},
					{"Dent", "Line A", null, 160},
					{"Dent", "Line C", 1, 100},
					{"Seal", "Line B", 4, 200},
					{"Seal", "Line A", 2, 160},
					{"Seal", "Line C", 0, 100},
					{"Label", "Line B", 2, 200},
					{"Label", "Line A", 4, 160}
				}),
				Typed = Table.TransformColumnTypes(Source, {{"Defect", type text}, {"Line", type text}, {"Defects", Int64.Type}, {"Opportunities", Int64.Type}}, "en-US")
			in
				Typed
