table 'DefectLine'

	measure 'Defect Count' =
			SUM ( DefectLine[Defects] )
		formatString: #,0

	measure 'Line Inspection Opportunities' =
			CALCULATE (
			SUMX (
			VALUES ( 'Line'[Line] ),
			CALCULATE ( MAX ( DefectLine[Opportunities] ) )
			),
			REMOVEFILTERS ( 'Defect' )
			)
		formatString: #,0

	measure 'Defect Records' =
			COUNTROWS ( DefectLine )
		formatString: #,0

	measure 'Defects Per Opportunity' =
			DIVIDE ( [Defect Count], [Line Inspection Opportunities] )
		formatString: 0.0%

	column 'Defect'
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: Defect

	column 'DefectSort'
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: DefectSort

	column 'Line'
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: Line

	column 'LineSort'
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: LineSort

	column 'Defects'
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: Defects

	column 'Opportunities'
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: Opportunities

	partition 'DefectLine' = m
		mode: import
		source =
			let
				Source = #table(type table [Defect = text, DefectSort = nullable number, Line = text, LineSort = nullable number, Defects = nullable number, Opportunities = nullable number], {
					{"Scratch", 10, "Line B", 10, 0, 200},
					{"Scratch", 10, "Line A", 20, 8, 160},
					{"Scratch", 10, "Line C", 30, 3, 100},
					{"Dent", 20, "Line B", 10, 6, 200},
					{"Dent", 20, "Line A", 20, null, 160},
					{"Dent", 20, "Line C", 30, 1, 100},
					{"Seal", 30, "Line B", 10, 4, 200},
					{"Seal", 30, "Line A", 20, 2, 160},
					{"Seal", 30, "Line C", 30, 0, 100},
					{"Label", 40, "Line B", 10, 2, 200},
					{"Label", 40, "Line A", 20, 4, 160}
				}),
				Typed = Table.TransformColumnTypes(Source, {{"Defect", type text}, {"DefectSort", Int64.Type}, {"Line", type text}, {"LineSort", Int64.Type}, {"Defects", Int64.Type}, {"Opportunities", Int64.Type}}, "en-US")
			in
				Typed
