table 'ProductRegion'

	measure 'Total Revenue' =
			SUM ( ProductRegion[Revenue] )
		formatString: $#,0;($#,0);$0

	measure 'Product Revenue Across Regions' =
			CALCULATE (
			[Total Revenue],
			REMOVEFILTERS ( 'Region' )
			)
		formatString: $#,0;($#,0);$0

	measure 'Revenue Records' =
			COUNTROWS ( ProductRegion )
		formatString: #,0

	measure 'Revenue Share Across Regions' =
			DIVIDE ( [Total Revenue], [Product Revenue Across Regions] )
		formatString: 0.0%

	column 'Product'
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: Product

	column 'Region'
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: Region

	column 'Revenue'
		dataType: double
		isHidden
		summarizeBy: none
		sourceColumn: Revenue

	partition 'ProductRegion' = m
		mode: import
		source =
			let
				Source = #table(type table [Product = text, Region = text, Revenue = nullable number], {
					{"Pumps", "North", 0},
					{"Pumps", "West", null},
					{"Pumps", "Central", 1200},
					{"Pumps", "East", 1800},
					{"Valves", "North", 2400},
					{"Valves", "West", 1600},
					{"Valves", "Central", 800},
					{"Valves", "East", 1200},
					{"Sensors", "North", 900},
					{"Sensors", "West", 1500},
					{"Sensors", "Central", 2100},
					{"Sensors", "East", 500},
					{"Filters", "North", 700},
					{"Filters", "West", 1300},
					{"Filters", "Central", 2000}
				}),
				Typed = Table.TransformColumnTypes(Source, {{"Product", type text}, {"Region", type text}, {"Revenue", type number}}, "en-US")
			in
				Typed
