table 'ProductRegion'

	measure 'Total Revenue' =
			SUM ( ProductRegion[Revenue] )
		formatString: $#,0;($#,0);$0

	measure 'Product Revenue Across Regions' =
			CALCULATE (
			[Total Revenue],
			REMOVEFILTERS ( 'Region' )
			)
		formatString: $#,0;($#,0);$0

	measure 'Revenue Records' =
			COUNTROWS ( ProductRegion )
		formatString: #,0

	measure 'Revenue Share Across Regions' =
			DIVIDE ( [Total Revenue], [Product Revenue Across Regions] )
		formatString: 0.0%

	column 'Product'
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: Product

	column 'ProductSort'
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: ProductSort

	column 'Region'
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: Region

	column 'RegionSort'
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: RegionSort

	column 'Revenue'
		dataType: double
		isHidden
		summarizeBy: none
		sourceColumn: Revenue

	partition 'ProductRegion' = m
		mode: import
		source =
			let
				Source = #table(type table [Product = text, ProductSort = nullable number, Region = text, RegionSort = nullable number, Revenue = nullable number], {
					{"Pumps", 10, "North", 10, 0},
					{"Pumps", 10, "West", 20, null},
					{"Pumps", 10, "Central", 30, 1200},
					{"Pumps", 10, "East", 40, 1800},
					{"Valves", 20, "North", 10, 2400},
					{"Valves", 20, "West", 20, 1600},
					{"Valves", 20, "Central", 30, 800},
					{"Valves", 20, "East", 40, 1200},
					{"Sensors", 30, "North", 10, 900},
					{"Sensors", 30, "West", 20, 1500},
					{"Sensors", 30, "Central", 30, 2100},
					{"Sensors", 30, "East", 40, 500},
					{"Filters", 40, "North", 10, 700},
					{"Filters", 40, "West", 20, 1300},
					{"Filters", 40, "Central", 30, 2000}
				}),
				Typed = Table.TransformColumnTypes(Source, {{"Product", type text}, {"ProductSort", Int64.Type}, {"Region", type text}, {"RegionSort", Int64.Type}, {"Revenue", type number}}, "en-US")
			in
				Typed
