import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";

const require = createRequire(import.meta.url);
const root = JSON.parse(readFileSync(new URL("../package.json", import.meta.url), "utf8"));
const visited = new Set();
const entries = [];
function visit(name, from) {
    const path = require.resolve(`${name}/package.json`, { paths: [from] });
    const pkg = JSON.parse(readFileSync(path, "utf8"));
    const key = `${pkg.name}@${pkg.version}`;
    if (visited.has(key)) return;
    visited.add(key);
    const directory = dirname(path);
    const licenses = readdirSync(directory).filter(file => /^(license|copying|notice)(\.|$)/i.test(file));
    if (!licenses.length) throw new Error(`Missing license for ${key}`);
    entries.push(`## ${key}\n\nLicense: ${pkg.license}. Source: ${typeof pkg.repository === "object" ? pkg.repository.url : pkg.repository || pkg.homepage}.\n\n${licenses.map(file => `### ${file}\n\n\`\`\`text\n${readFileSync(join(directory, file), "utf8").trim()}\n\`\`\``).join("\n\n")}`);
    for (const dependency of Object.keys(pkg.dependencies || {}).sort()) visit(dependency, directory);
}
for (const name of Object.keys(root.dependencies).sort()) visit(name, process.cwd());
const scaffoldLicensePath = require.resolve("powerbi-visuals-tools/LICENSE");
if (!existsSync(scaffoldLicensePath)) throw new Error("SDK scaffold license missing");
const header = "# Third-party notices\n\nGenerated by `npm run notices` from the locked production dependency graph. These notices do not license Atlyn's original code. Build/test tooling is development-only, reviewable in package-lock.json; npm retains each tool's own license under node_modules.\n\n## Microsoft Power BI visual scaffold\n\nScaffolded with powerbi-visuals-tools 7.2.1. Microsoft MIT notice:\n\n```text\n" + readFileSync(scaffoldLicensePath, "utf8").trim() + "\n```\n\n";
const text = header + entries.sort().join("\n\n") + "\n";
writeFileSync(new URL("../THIRD_PARTY_NOTICES.md", import.meta.url), text);
writeFileSync(new URL("../src/thirdParty.json", import.meta.url), JSON.stringify({ text }, null, 2) + "\n");
console.log(`Wrote production notices for ${visited.size} packages plus SDK scaffold.`);
